version: '3'

volumes:
  pg-data-kc:
  pg-data-hub:

services:
  nginx:
    build: nginx/.
    container_name: nginx
    restart: on-failure
    ports:
      - "8080:8080"
  keycloak:
    build: keycloak/.
    container_name: keycloak
    restart: on-failure
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-kc
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
  postgres-kc:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data-kc:/var/lib/postgresql/data
  jupyterhub:
    build: jupyterhub/.
    container_name: jupyterhub
    restart: on-failure
    env_file:
      - .env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
  postgres-hub:
    image: postgres
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_USER: jupyterhub
      POSTGRES_PASSWORD: password
    volumes:
       - pg-data-hub:/var/lib/postgresql/data
