version: '3'

volumes:
  pg-data:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: keycloak
    ports:
      - 8080:8080
  jupyterhub:
    image: illumidesk/jupyterhub:k8s
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    env_file:
      - .env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
  postgres:
    image: illumidesk/postgres:k8s
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
