kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-persist
  namespace: apple-test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
